name: 'OCaml tests'

on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master
jobs:
  run:
    name: Build
    runs-on: '${{ matrix.os }}'
    steps:
      - name: 'Install deps'
        run: bash -c '''case "$(uname)" in
          (*Linux*) sudo apt-get update && sudo apt-get install -y libffi-dev libopenimageio-dev; ;;
          (*Darwin*) brew install openimageio libffi; ;;
          esac'''
      - name: 'Checkout code'
        uses: actions/checkout@v2
      - name: 'Use OCaml ${{ matrix.ocaml-compiler }}'
        uses: ocaml/setup-ocaml@v3
        with:
          ocaml-compiler: '${{ matrix.ocaml-compiler }}'
          opam-local-packages: 'bimage.opam bimage-unix.opam'
      - run: 'opam install dune ctypes ctypes-foreign'
      - name: 'Run OCaml tests'
        run: 'opam exec -- dune runtest'
    strategy:
      fail-fast: true
      matrix:
        ocaml-compiler:
          - 5.2.0
        os:
          - macos-latest
          - ubuntu-latest
